#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cp -r initial/* 0

rm -rf 0/cellLevel 0/pointLevel
rm -f ./*.obj
rm -rf constant/extendedFeatureEdgeMesh
rm -rf constant/triSurface/*.eMesh
rm -rf constant/polyMesh
rm -rf fluentInterface

cleanCase

# ----------------------------------------------------------------- end-of-file
