#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
runApplication surfaceFeatureExtract
runApplication snappyHexMesh -overwrite
runApplication checkMesh

cp -r initial/* 0/
runApplication potentialFoam
runApplication icoFoam

runApplication foamMeshToFluent
runApplication foamDataToFluent
