#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Set application name
application=$(getApplication)

# Get number of processors to run on
nProcs=$(getNumberOfProcessors)

\rm -rf 0

runApplication blockMesh
# runApplication decomposePar
runApplication surfaceFeatureExtract

#runParallel snappyHexMesh $nProcs
#runParallel collapseEdges $nProcs -collapseFaces -latestTime
#runParallel checkMesh $nProcs -allTopology -allGeometry -latestTime

runApplication snappyHexMesh -overwrite
# runApplication collapseEdges -collapseFaces -latestTime
runApplication checkMesh -allTopology -allGeometry

# runApplication reconstructParMesh -latestTime
