#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

rm log.potentialFoam log.pimpleFoam
rm -rf 0/*
find -type d -name '[0-9]*.[0.9]*' | xargs rm -rf

cp -r initial/* 0/
# potentialFoam
pimpleFoam

rm -rf fluentInterface
foamMeshToFluent
foamDataToFluent
