#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase

\rm -rf 0
# \rm -f constant/polyMesh
\rm -rf constant/extendedFeatureEdgeMesh/
\rm -f constant/triSurface/*.eMesh*
\rm -f constant/triSurface/*.obj
\rm -f constant/triSurface/problemFaces
\rm -f *.obj

# ----------------------------------------------------------------- end-of-file
