#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

rm -rf 0
cp -r initial 0

runApplication blockMesh
runApplication surfaceFeatureExtract

runApplication snappyHexMesh -overwrite
runApplication checkMesh -allTopology -allGeometry

runApplication pimpleFoam
