
task :mesh do
	sh("openscad", "../source/duct.scad", "-o", "../build/duct.stl", "-Dvent_count=#{ENV.fetch('VENT_COUNT', 3)}") 
end

task :convert_to_meters => :mesh do
	sh("surfaceTransformPoints", "-scale", "(0.001 0.001  0.001)", "../build/duct.stl", "duct_scaled.stl")
	sh("surfaceTransformPoints", "-scale", "(0.001 0.001  0.001)", "../build/intake.stl", "intake_scaled.stl")
end

task :constants => :convert_to_meters do
	duct_stl = File.readlines("duct_scaled.stl")
	intake_stl = File.readlines("intake_scaled.stl")
	
	duct_stl.first.replace("solid duct")
	duct_stl.last.replace("endsolid duct")
	intake_stl.first.replace("solid intake")
	intake_stl.last.replace("endsolid intake")
	
	File.open("constant/triSurface/duct.stl", "w") do |file|
		file.puts duct_stl
	end
	
	File.open("constant/triSurface/intake.stl", "w") do |file|
		file.puts intake_stl
	end
end

task :default => :constants
